watch_stylesheet: true
watch_config: true
bars:
  status-bar:
    enabled: true
    screens: ['*']
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: true
    blur_effect:
      enabled: true
      acrylic: true
      dark_mode: true
      round_corners: true
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 40
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left:
        ["power_menu", "home", "note", "code", "web"]
      center: ["clock", "active_window"]
      right:
        ["github", "media_player", "memory", "volume", "wifi", "battery"]
widgets:
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "{win[class_name]} ({win[process][name]})"
      label_no_window: "No Active Window"
      max_length: 50
      label_icon: true
      label_icon_size: 16
      max_length_ellipsis: ".."
      monitor_exclusive: false

  battery:
      type: "yasb.battery.BatteryWidget"
      options:
        label: "<span>{icon}</span> {percent}%"
        label_alt: "{percent}% | {time_remaining}"
        charging_options:
          icon_format: "{charging_icon}"
        status_icons:
          icon_charging: "\uf0e7"  # fa-bolt
          icon_critical: "\uf244"  # fa-battery-empty
          icon_low: "\uf243"  # fa-battery-quarter
          icon_medium: "\uf242"  # fa-battery-half
          icon_high: "\uf241"  # fa-battery-three-quarters
          icon_full: "\uf240"  # fa-battery-full

  github:
    type: "yasb.github.GithubWidget"
    options:
      label: "<span>Github</span>"
      label_alt: "{data} Notifications"
      token: env
      update_interval: 60

  clock:
      type: "yasb.clock.ClockWidget"
      options:
        label: "{%a %I:%M %p}"
        label_alt: "{%A %d %B %Y %I:%M %p %Z}"
        callbacks:
          on_middle: "exec explorer.exe shell:Appsfolder\\Microsoft.WindowsAlarms_8wekyb3d8bbwe!App"

  memory:
      type: "yasb.memory.MemoryWidget"
      options:
        label: "\uf538 {virtual_mem_percent}%"
        label_alt: "RAM: {virtual_mem_used} / {virtual_mem_total} GB"
        update_interval: 5000

  wifi:
      type: "yasb.wifi.WifiWidget"
      options:
        label: "\uf1eb {wifi_name}"
        label_alt: "Wi-Fi: {wifi_signal}%"
        update_interval: 5000

  volume:
      type: "yasb.volume.VolumeWidget"
      options:
        label: "{icon} {level}"
        volume_icons:
          - "\uf026"  # Mute
          - "\uf027"  # Low
          - "\uf028"  # Medium
          - "\uf6a8"  # High

  media_player:
        type: "yasb.media.MediaWidget"
        options:
          label: "{title} - {artist}"
          label_alt: "{title}"
          show_thumbnail: true

  weather:
      type: "yasb.weather.WeatherWidget"
      options:
        label: "{icon} {temp}°C"
        label_alt: "{min_temp}° - {max_temp}° | {humidity}%"
        api_key: 'YOUR_API_KEY'
        update_interval: 600

  power_menu:
      type: "yasb.power_menu.PowerMenuWidget"
      options:
        label: "<span>microsoft</span>" # fa-brands fa-apple
        blur_background: true
        animation_duration: 200
        button_row: 3
        buttons:
          lock: ["\uf023","Lock"] # fa-solid fa-lock
          signout: ["\uf2f5","Sign out"] #fa-solid fa-sign-out-alt
          sleep: ["\uf1da","Sleep"]  # fa-solid fa-power-off
          shutdown: ["\uf011","Shut Down"] # fa-solid fa-power-off
          restart: ["\uf0e7","Restart"] # fa-solid fa-bolt
          hibernate: ["\uf0a5","Hibernate"] # fa-solid fa-moon
          cancel: ["\uf05e","Cancel"] # fa-solid fa-times

  weather:
      type: "yasb.weather.WeatherWidget"
      options:
        label: "<span>{icon}</span> {temp}"
        label_alt: "Min {min_temp}, Max {max_temp}, Humidity {humidity}"
        api_key: 'YOUR_API_KEY' # Replace with your WeatherAPI key
        update_interval: 600
        hide_decimal: true
        location: 'Doha'
        callbacks:
          on_left: "toggle_label"
        icons:
          sunnyDay: "\uf185" # fa-solid fa-sun
          clearNight: "\uf186" # fa-solid fa-moon
          cloudyDay: "\uf002"  # fa-solid fa-cloud
          cloudyNight: "\uf002" # fa-solid fa-cloud
          rainyDay: "\uf73d" # fa-solid fa-cloud-rain
          rainyNight: "\uf73d" # fa-solid fa-cloud-rain
          snowyIcyDay: "\uf2dc" # fa-solid fa-snowflake
          snowyIcyNight: "\uf2dc" # fa-solid fa-snowflake
          blizzard: "\uf6dd" # fa-solid fa-wind
          default: "\uf00d" #fa-solid fa-question

  notification_button:
      type: "yasb.custom.CustomWidget"
      options:
        label: "<span>\uf0f3</span>" # fa-solid fa-bell
        label_alt: "<span>\uf0f3</span> Notifications" # fa-solid fa-bell
        class_name: "notification-widget"
        callbacks:
          on_left: "exec notification_center"
          on_right: "toggle_label"

  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>Start</span>"
      menu_list:
      - { title: "User Home", path: "~" }
      - { title: "Download", path: "C:\\Users\\97466Downloads" }
      - { title: "Documents", path: "C:\\Users\\97466\\Documents" }
      - { title: "Pictures", path: "C:\\Users\\97466\\Pictures" }
      system_menu: true
      power_menu: true
      blur: true
      round_corners: true
      border_color: None
      distance: 4
      menu_labels:
        shutdown: "Shutdown"
        restart: "Restart"
        logout: "Logout"
        lock: "Lock"
        sleep: "Sleep"
        system: "System Settings"
        about: "About This PC"
        task_manager: "Task Manager"

  note:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>Note</span>"
      menu_list:
      - { title: "New Note", path: "C:\\WINDOWS\\system32\\notepad.exe" }
      system_menu: false
      power_menu: false
      blur: true
      round_corners: true
      border_color: None
      distance: 4

  code:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>Code</span>"
      menu_list:
      - { title: "PyCharm Professional", path: "C:\\Program Files\\JetBrains\\PyCharm 2024.2.3\\bin\\pycharm64.exe" }
      - { title: "Visual Studio Code", path: "C:\\Users\\97466\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" }
      - { title: "Notepad", path: "C:\\WINDOWS\\system32\\notepad.exe" }
      - { title: "Python", path: "C:\\Users\\97466\\AppData\\Local\\Programs\\Python\\Python310\\python.exe" }
      - { title: "Terminal", path: "C:\\Users\\97466\\AppData\\Local\\Microsoft\\WindowsApps\\wt.exe" }
      system_menu: false
      power_menu: false
      blur: true
      round_corners: true
      border_color: None
      distance: 4

  web:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>Web</span>"
      menu_list:
      - { title: "New Firefox Window", path: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" }
      - { title: "New Edge Window", path: "C:\\Program Files\\Deskime Browser\\deskime.pyw" }
      system_menu: false
      power_menu: false
      blur: true
      round_corners: true
      border_color: None
      distance: 4